import Providers from '@/components/Providers';
import { TopNav } from '../components/navbar/TopNav';
import './global.css';
import LandGuard from '@/components/LandGuard';

export const metadata = {
  title: 'Welcome to portfolio',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="font-popins portfolio-theme text-color-text-black">
        <Providers>
          <LandGuard>
            <TopNav />
            {children}
          </LandGuard>
        </Providers>
      </body>
    </html>
  );
}
