import { ServiceRouteCreateRequest } from '@frankjhub/shared-schema';
import { SYSTEM_SERVICES } from '../../common/constants/system-services';

export const SYSTEM_SERVICE_ROUTE_KEY_LIST = [
  'AUTH',
  'JWKS',
  'USER_LIST',
  'USER_DETAIL',
  'USER_SOFT_DELETE',
  'USER_HARD_DELETE',
  'USER_RESTORE',
  'USER_UPDATE',
  'USER_CURRENT',
  'USER_OPTION_LIST',
  'ORG_TYPE_LIST',
  'ORG_TYPE_OPTION_LIST',
  'ORG_TYPE_DETAIL',
  'ORG_TYPE_SOFT_DELETE',
  'ORG_TYPE_HARD_DELETE',
  'ORG_TYPE_RESTORE',
  'ORG_TYPE_UPDATE',
  'ORG_TYPE_CREATE',
  'ACTION_LIST',
  'ACTION_OPTION_LIST',
  'ACTION_DETAIL',
  'ACTION_SOFT_DELETE',
  'ACTION_HARD_DELETE',
  'ACTION_RESTORE',
  'ACTION_UPDATE',
  'ACTION_CREATE',
  'RESOURCE_LIST',
  'RESOURCE_OPTION_LIST',
  'RESOURCE_DETAIL',
  'RESOURCE_SOFT_DELETE',
  'RESOURCE_HARD_DELETE',
  'RESOURCE_RESTORE',
  'RESOURCE_UPDATE',
  'RESOURCE_CREATE',
  'PERMISSION_LIST',
  'PERMISSION_OPTION_LIST',
  'PERMISSION_DETAIL',
  'PERMISSION_SOFT_DELETE',
  'PERMISSION_HARD_DELETE',
  'PERMISSION_RESTORE',
  'PERMISSION_UPDATE',
  'PERMISSION_CREATE',
  'ROLE_LIST',
  'ROLE_LIST_SEARCH',
  'ROLE_OPTION_LIST',
  'ROLE_DETAIL',
  'ROLE_SOFT_DELETE',
  'ROLE_HARD_DELETE',
  'ROLE_RESTORE',
  'ROLE_UPDATE',
  'ROLE_CREATE',
  'ORGANIZATION_LIST',
  'ORGANIZATION_DETAIL',
  'ORGANIZATION_SOFT_DELETE',
  'ORGANIZATION_HARD_DELETE',
  'ORGANIZATION_RESTORE',
  'ORGANIZATION_UPDATE',
  'ORGANIZATION_CREATE',
  'ORGANIZATION_OPTION_LIST',
  'USER_ORG_ROLE_UPDATE',
  'USER_ORG_ROLE_DETAIL',
  'SERVICE_LIST',
] as const;

export type SystemServiceRouteKey = (typeof SYSTEM_SERVICE_ROUTE_KEY_LIST)[number];

export const SYSTEM_SERVICE_ROUTES: Record<
  SystemServiceRouteKey,
  ServiceRouteCreateRequest & { scopes: string[] }
> = {
  // Auth
  AUTH: {
    path: '/auth',
    serviceId: SYSTEM_SERVICES.MAIN.serviceId,
    methods: ['POST', 'GET'],
    routeRuleType: 'prefix',
    rewrite: null,
    isActive: true,
    authMode: 'all',
    scopes: [],
  },
  JWKS: {
    path: '/.well-known/jwks.json',
    serviceId: SYSTEM_SERVICES.MAIN.serviceId,
    methods: ['GET'],
    routeRuleType: 'exact',
    rewrite: null,
    isActive: true,
    authMode: 'all',
    scopes: [],
  },
  // USER
  USER_LIST: {
    path: '/user/list',
    serviceId: SYSTEM_SERVICES.MAIN.serviceId,
    methods: ['GET'],
    routeRuleType: 'exact',
    rewrite: null,
    isActive: true,
    authMode: 'all',
    scopes: ['main.user:read'],
  },
  USER_DETAIL: {
    path: '/user/:id',
    serviceId: SYSTEM_SERVICES.MAIN.serviceId,
    methods: ['GET'],
    routeRuleType: 'exact',
    rewrite: null,
    isActive: true,
    authMode: 'all',
    scopes: ['main.user.:id:read'],
  },
  USER_SOFT_DELETE: {
    path: '/user/soft-delete',
    serviceId: SYSTEM_SERVICES.MAIN.serviceId,
    methods: ['PATCH'],
    routeRuleType: 'exact',
    rewrite: null,
    isActive: true,
    authMode: 'all',
    scopes: ['main.user:soft_delete'],
  },
  USER_HARD_DELETE: {
    path: '/user/hard-delete',
    serviceId: SYSTEM_SERVICES.MAIN.serviceId,
    methods: ['DELETE'],
    routeRuleType: 'exact',
    rewrite: null,
    isActive: true,
    authMode: 'all',
    scopes: ['main.user:hard_delete'],
  },
  USER_RESTORE: {
    path: '/user/restore',
    serviceId: SYSTEM_SERVICES.MAIN.serviceId,
    methods: ['PATCH'],
    routeRuleType: 'exact',
    rewrite: null,
    isActive: true,
    authMode: 'all',
    scopes: ['main.user:restore'],
  },
  USER_UPDATE: {
    path: '/user/update',
    serviceId: SYSTEM_SERVICES.MAIN.serviceId,
    methods: ['PATCH'],
    routeRuleType: 'exact',
    rewrite: null,
    isActive: true,
    authMode: 'all',
    scopes: ['main.user:update'],
  },
  USER_CURRENT: {
    path: '/user/current-user',
    serviceId: SYSTEM_SERVICES.MAIN.serviceId,
    methods: ['GET'],
    routeRuleType: 'exact',
    rewrite: null,
    isActive: true,
    authMode: 'all',
    scopes: [],
  },
  USER_OPTION_LIST: {
    path: '/user/options',
    serviceId: SYSTEM_SERVICES.MAIN.serviceId,
    methods: ['GET'],
    routeRuleType: 'exact',
    rewrite: null,
    isActive: true,
    authMode: 'all',
    scopes: ['main.user:list'],
  },
  // ORGNIZATION TYPE
  ORG_TYPE_LIST: {
    path: '/organization-type/list',
    serviceId: SYSTEM_SERVICES.MAIN.serviceId,
    methods: ['GET'],
    routeRuleType: 'exact',
    rewrite: null,
    isActive: true,
    authMode: 'all',
    scopes: ['main.organizationType:read'],
  },
  ORG_TYPE_OPTION_LIST: {
    path: '/organization-type/options',
    serviceId: SYSTEM_SERVICES.MAIN.serviceId,
    methods: ['GET'],
    routeRuleType: 'exact',
    rewrite: null,
    isActive: true,
    authMode: 'all',
    scopes: ['main.organizationType:list'],
  },
  ORG_TYPE_DETAIL: {
    path: '/organization-type/:id',
    serviceId: SYSTEM_SERVICES.MAIN.serviceId,
    methods: ['GET'],
    routeRuleType: 'exact',
    rewrite: null,
    isActive: true,
    authMode: 'all',
    scopes: ['main.organizationType.:id:read'],
  },
  ORG_TYPE_SOFT_DELETE: {
    path: '/organization-type/soft-delete',
    serviceId: SYSTEM_SERVICES.MAIN.serviceId,
    methods: ['PATCH'],
    routeRuleType: 'exact',
    rewrite: null,
    isActive: true,
    authMode: 'all',
    scopes: ['main.organizationType:soft_delete'],
  },
  ORG_TYPE_HARD_DELETE: {
    path: '/organization-type/soft-delete',
    serviceId: SYSTEM_SERVICES.MAIN.serviceId,
    methods: ['DELETE'],
    routeRuleType: 'exact',
    rewrite: null,
    isActive: true,
    authMode: 'all',
    scopes: ['main.organizationType:hard_delete'],
  },
  ORG_TYPE_RESTORE: {
    path: '/organization-type/restore',
    serviceId: SYSTEM_SERVICES.MAIN.serviceId,
    methods: ['PATCH'],
    routeRuleType: 'exact',
    rewrite: null,
    isActive: true,
    authMode: 'all',
    scopes: ['main.organizationType:restore'],
  },
  ORG_TYPE_UPDATE: {
    path: '/organization-type/update',
    serviceId: SYSTEM_SERVICES.MAIN.serviceId,
    methods: ['PATCH'],
    routeRuleType: 'exact',
    rewrite: null,
    isActive: true,
    authMode: 'all',
    scopes: ['main.organizationType:update'],
  },
  ORG_TYPE_CREATE: {
    path: '/organization-type',
    serviceId: SYSTEM_SERVICES.MAIN.serviceId,
    methods: ['POST'],
    routeRuleType: 'exact',
    rewrite: null,
    isActive: true,
    authMode: 'all',
    scopes: ['main.organizationType:create'],
  },
  ACTION_LIST: {
    path: '/action/list',
    serviceId: SYSTEM_SERVICES.MAIN.serviceId,
    methods: ['GET'],
    routeRuleType: 'exact',
    rewrite: null,
    isActive: true,
    authMode: 'all',
    scopes: ['main.action:read'],
  },
  ACTION_OPTION_LIST: {
    path: '/action/options',
    serviceId: SYSTEM_SERVICES.MAIN.serviceId,
    methods: ['GET'],
    routeRuleType: 'exact',
    rewrite: null,
    isActive: true,
    authMode: 'all',
    scopes: ['main.action:list'],
  },
  ACTION_DETAIL: {
    path: '/action/:id',
    serviceId: SYSTEM_SERVICES.MAIN.serviceId,
    methods: ['GET'],
    routeRuleType: 'exact',
    rewrite: null,
    isActive: true,
    authMode: 'all',
    scopes: ['main.action.:id:read'],
  },
  ACTION_SOFT_DELETE: {
    path: '/action/soft-delete',
    serviceId: SYSTEM_SERVICES.MAIN.serviceId,
    methods: ['PATCH'],
    routeRuleType: 'exact',
    rewrite: null,
    isActive: true,
    authMode: 'all',
    scopes: ['main.action:soft_delete'],
  },
  ACTION_HARD_DELETE: {
    path: '/action/hard-delete',
    serviceId: SYSTEM_SERVICES.MAIN.serviceId,
    methods: ['DELETE'],
    routeRuleType: 'exact',
    rewrite: null,
    isActive: true,
    authMode: 'all',
    scopes: ['main.action:hard_delete'],
  },
  ACTION_RESTORE: {
    path: '/action/restore',
    serviceId: SYSTEM_SERVICES.MAIN.serviceId,
    methods: ['PATCH'],
    routeRuleType: 'exact',
    rewrite: null,
    isActive: true,
    authMode: 'all',
    scopes: ['main.action:restore'],
  },
  ACTION_UPDATE: {
    path: '/action/update',
    serviceId: SYSTEM_SERVICES.MAIN.serviceId,
    methods: ['PATCH'],
    routeRuleType: 'exact',
    rewrite: null,
    isActive: true,
    authMode: 'all',
    scopes: ['main.action:update'],
  },
  ACTION_CREATE: {
    path: '/action',
    serviceId: SYSTEM_SERVICES.MAIN.serviceId,
    methods: ['POST'],
    routeRuleType: 'exact',
    rewrite: null,
    isActive: true,
    authMode: 'all',
    scopes: ['main.action:create'],
  },

  // RESOURCE
  RESOURCE_LIST: {
    path: '/resource/list',
    serviceId: SYSTEM_SERVICES.MAIN.serviceId,
    methods: ['GET'],
    routeRuleType: 'exact',
    rewrite: null,
    isActive: true,
    authMode: 'all',
    scopes: ['main.resource:read'],
  },
  RESOURCE_OPTION_LIST: {
    path: '/resource/options',
    serviceId: SYSTEM_SERVICES.MAIN.serviceId,
    methods: ['GET'],
    routeRuleType: 'exact',
    rewrite: null,
    isActive: true,
    authMode: 'all',
    scopes: ['main.resource:list'],
  },
  RESOURCE_DETAIL: {
    path: '/resource/:id',
    serviceId: SYSTEM_SERVICES.MAIN.serviceId,
    methods: ['GET'],
    routeRuleType: 'exact',
    rewrite: null,
    isActive: true,
    authMode: 'all',
    scopes: ['main.resource.:id:read'],
  },
  RESOURCE_SOFT_DELETE: {
    path: '/resource/soft-delete',
    serviceId: SYSTEM_SERVICES.MAIN.serviceId,
    methods: ['PATCH'],
    routeRuleType: 'exact',
    rewrite: null,
    isActive: true,
    authMode: 'all',
    scopes: ['main.resource:soft_delete'],
  },
  RESOURCE_HARD_DELETE: {
    path: '/resource/hard-delete',
    serviceId: SYSTEM_SERVICES.MAIN.serviceId,
    methods: ['DELETE'],
    routeRuleType: 'exact',
    rewrite: null,
    isActive: true,
    authMode: 'all',
    scopes: ['main.resource:hard_delete'],
  },
  RESOURCE_RESTORE: {
    path: '/resource/restore',
    serviceId: SYSTEM_SERVICES.MAIN.serviceId,
    methods: ['PATCH'],
    routeRuleType: 'exact',
    rewrite: null,
    isActive: true,
    authMode: 'all',
    scopes: ['main.resource:restore'],
  },
  RESOURCE_UPDATE: {
    path: '/resource/update',
    serviceId: SYSTEM_SERVICES.MAIN.serviceId,
    methods: ['PATCH'],
    routeRuleType: 'exact',
    rewrite: null,
    isActive: true,
    authMode: 'all',
    scopes: ['main.resource:update'],
  },
  RESOURCE_CREATE: {
    path: '/resource',
    serviceId: SYSTEM_SERVICES.MAIN.serviceId,
    methods: ['POST'],
    routeRuleType: 'exact',
    rewrite: null,
    isActive: true,
    authMode: 'all',
    scopes: ['main.resource:create'],
  },

  // PERMISSION
  PERMISSION_LIST: {
    path: '/permission/list',
    serviceId: SYSTEM_SERVICES.MAIN.serviceId,
    methods: ['GET'],
    routeRuleType: 'exact',
    rewrite: null,
    isActive: true,
    authMode: 'all',
    scopes: ['main.permission:read'],
  },
  PERMISSION_OPTION_LIST: {
    path: '/permission/options',
    serviceId: SYSTEM_SERVICES.MAIN.serviceId,
    methods: ['GET'],
    routeRuleType: 'exact',
    rewrite: null,
    isActive: true,
    authMode: 'all',
    scopes: ['main.permission:list'],
  },
  PERMISSION_DETAIL: {
    path: '/permission/:id',
    serviceId: SYSTEM_SERVICES.MAIN.serviceId,
    methods: ['GET'],
    routeRuleType: 'exact',
    rewrite: null,
    isActive: true,
    authMode: 'all',
    scopes: ['main.permission.:id:read'],
  },
  PERMISSION_SOFT_DELETE: {
    path: '/permission/soft-delete',
    serviceId: SYSTEM_SERVICES.MAIN.serviceId,
    methods: ['PATCH'],
    routeRuleType: 'exact',
    rewrite: null,
    isActive: true,
    authMode: 'all',
    scopes: ['main.permission:soft_delete'],
  },
  PERMISSION_HARD_DELETE: {
    path: '/permission/hard-delete',
    serviceId: SYSTEM_SERVICES.MAIN.serviceId,
    methods: ['DELETE'],
    routeRuleType: 'exact',
    rewrite: null,
    isActive: true,
    authMode: 'all',
    scopes: ['main.permission:hard_delete'],
  },
  PERMISSION_RESTORE: {
    path: '/permission/restore',
    serviceId: SYSTEM_SERVICES.MAIN.serviceId,
    methods: ['PATCH'],
    routeRuleType: 'exact',
    rewrite: null,
    isActive: true,
    authMode: 'all',
    scopes: ['main.permission:restore'],
  },
  PERMISSION_UPDATE: {
    path: '/permission/update',
    serviceId: SYSTEM_SERVICES.MAIN.serviceId,
    methods: ['PATCH'],
    routeRuleType: 'exact',
    rewrite: null,
    isActive: true,
    authMode: 'all',
    scopes: ['main.permission:update'],
  },
  PERMISSION_CREATE: {
    path: '/permission',
    serviceId: SYSTEM_SERVICES.MAIN.serviceId,
    methods: ['POST'],
    routeRuleType: 'exact',
    rewrite: null,
    isActive: true,
    authMode: 'all',
    scopes: ['main.permission:create'],
  },

  // ROLE
  ROLE_LIST: {
    path: '/role/list',
    serviceId: SYSTEM_SERVICES.MAIN.serviceId,
    methods: ['GET'],
    routeRuleType: 'exact',
    rewrite: null,
    isActive: true,
    authMode: 'all',
    scopes: ['main.role:read'],
  },
  ROLE_LIST_SEARCH: {
    path: '/role/list/search',
    serviceId: SYSTEM_SERVICES.MAIN.serviceId,
    methods: ['POST'],
    routeRuleType: 'exact',
    rewrite: null,
    isActive: true,
    authMode: 'all',
    scopes: ['main.role:search'],
  },
  ROLE_OPTION_LIST: {
    path: '/role/options',
    serviceId: SYSTEM_SERVICES.MAIN.serviceId,
    methods: ['GET'],
    routeRuleType: 'exact',
    rewrite: null,
    isActive: true,
    authMode: 'all',
    scopes: ['main.role:list'],
  },
  ROLE_DETAIL: {
    path: '/role/:id',
    serviceId: SYSTEM_SERVICES.MAIN.serviceId,
    methods: ['GET'],
    routeRuleType: 'exact',
    rewrite: null,
    isActive: true,
    authMode: 'all',
    scopes: ['main.role.:id:read'],
  },
  ROLE_SOFT_DELETE: {
    path: '/role/soft-delete',
    serviceId: SYSTEM_SERVICES.MAIN.serviceId,
    methods: ['PATCH'],
    routeRuleType: 'exact',
    rewrite: null,
    isActive: true,
    authMode: 'all',
    scopes: ['main.role:soft_delete'],
  },
  ROLE_HARD_DELETE: {
    path: '/role/hard-delete',
    serviceId: SYSTEM_SERVICES.MAIN.serviceId,
    methods: ['DELETE'],
    routeRuleType: 'exact',
    rewrite: null,
    isActive: true,
    authMode: 'all',
    scopes: ['main.role:hard_delete'],
  },
  ROLE_RESTORE: {
    path: '/role/restore',
    serviceId: SYSTEM_SERVICES.MAIN.serviceId,
    methods: ['PATCH'],
    routeRuleType: 'exact',
    rewrite: null,
    isActive: true,
    authMode: 'all',
    scopes: ['main.role:restore'],
  },
  ROLE_UPDATE: {
    path: '/role/update',
    serviceId: SYSTEM_SERVICES.MAIN.serviceId,
    methods: ['PATCH'],
    routeRuleType: 'exact',
    rewrite: null,
    isActive: true,
    authMode: 'all',
    scopes: ['main.role:update'],
  },
  ROLE_CREATE: {
    path: '/role',
    serviceId: SYSTEM_SERVICES.MAIN.serviceId,
    methods: ['POST'],
    routeRuleType: 'exact',
    rewrite: null,
    isActive: true,
    authMode: 'all',
    scopes: ['main.role:create'],
  },

  // ORGANIZATION
  ORGANIZATION_LIST: {
    path: '/organization/list',
    serviceId: SYSTEM_SERVICES.MAIN.serviceId,
    methods: ['GET'],
    routeRuleType: 'exact',
    rewrite: null,
    isActive: true,
    authMode: 'all',
    scopes: ['main.organization:read'],
  },
  ORGANIZATION_DETAIL: {
    path: '/organization/:id',
    serviceId: SYSTEM_SERVICES.MAIN.serviceId,
    methods: ['GET'],
    routeRuleType: 'exact',
    rewrite: null,
    isActive: true,
    authMode: 'all',
    scopes: ['main.organization.:id:read'],
  },
  ORGANIZATION_SOFT_DELETE: {
    path: '/organization/soft-delete',
    serviceId: SYSTEM_SERVICES.MAIN.serviceId,
    methods: ['PATCH'],
    routeRuleType: 'exact',
    rewrite: null,
    isActive: true,
    authMode: 'all',
    scopes: ['main.organization:soft_delete'],
  },
  ORGANIZATION_HARD_DELETE: {
    path: '/organization/hard-delete',
    serviceId: SYSTEM_SERVICES.MAIN.serviceId,
    methods: ['DELETE'],
    routeRuleType: 'exact',
    rewrite: null,
    isActive: true,
    authMode: 'all',
    scopes: ['main.organization:hard_delete'],
  },
  ORGANIZATION_RESTORE: {
    path: '/organization/restore',
    serviceId: SYSTEM_SERVICES.MAIN.serviceId,
    methods: ['PATCH'],
    routeRuleType: 'exact',
    rewrite: null,
    isActive: true,
    authMode: 'all',
    scopes: ['main.organization:restore'],
  },
  ORGANIZATION_UPDATE: {
    path: '/organization/update',
    serviceId: SYSTEM_SERVICES.MAIN.serviceId,
    methods: ['PATCH'],
    routeRuleType: 'exact',
    rewrite: null,
    isActive: true,
    authMode: 'all',
    scopes: ['main.organization:update'],
  },
  ORGANIZATION_CREATE: {
    path: '/organization',
    serviceId: SYSTEM_SERVICES.MAIN.serviceId,
    methods: ['POST'],
    routeRuleType: 'exact',
    rewrite: null,
    isActive: true,
    authMode: 'all',
    scopes: ['main.organization:create'],
  },
  ORGANIZATION_OPTION_LIST: {
    path: '/organization/options',
    serviceId: SYSTEM_SERVICES.MAIN.serviceId,
    methods: ['GET'],
    routeRuleType: 'exact',
    rewrite: null,
    isActive: true,
    authMode: 'all',
    scopes: ['main.organization:list'],
  },

  // USER ORGANIZATION ROLE
  USER_ORG_ROLE_UPDATE: {
    path: '/user-organization-role/update',
    serviceId: SYSTEM_SERVICES.MAIN.serviceId,
    methods: ['PATCH'],
    routeRuleType: 'exact',
    rewrite: null,
    isActive: true,
    authMode: 'all',
    scopes: ['main.userOrganizationRole:update'],
  },
  USER_ORG_ROLE_DETAIL: {
    path: '/user-organization-role/:id',
    serviceId: SYSTEM_SERVICES.MAIN.serviceId,
    methods: ['GET'],
    routeRuleType: 'exact',
    rewrite: null,
    isActive: true,
    authMode: 'all',
    scopes: ['main.userOrganizationRole.:id:read'],
  },

  // SERVICE
  SERVICE_LIST: {
    path: '/service/list',
    serviceId: SYSTEM_SERVICES.MAIN.serviceId,
    methods: ['GET'],
    routeRuleType: 'exact',
    rewrite: null,
    isActive: true,
    authMode: 'all',
    scopes: ['main.service:read'],
  },
};
